name: birthday_reminder
description: Birthday Reminder APP.

publish_to: "none"

version: "2.0.1+5"

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.15.2
  flutter_localizations:
    sdk: flutter
  intl: any
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  provider: ^6.0.5
  flutter_signin_button: ^2.0.0
  settings_ui: ^2.0.2
  carousel_slider: ^5.1.1
  modal_bottom_sheet: ^3.0.0
  universal_html: ^2.2.3
  firebase_messaging: ^15.2.10
  firebase_notifications_handler: ^2.0.2+1
  app_settings: ^6.1.1
  shared_preferences: ^2.1.1
  uuid: ^4.5.1
  firebase_remote_config: ^5.5.0
  share_plus: ^11.1.0
  js: ^0.7.2
  url_launcher: ^6.1.11
  app_links: ^6.4.1
  characters: ^1.3.0
  url_launcher_web: ^2.4.1

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#2196F3"
