name: birthday_reminder
description: Birthday Reminder APP.

publish_to: "none"

version: "2.0.0"

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.0
  flutter_localizations:
    sdk: flutter
  intl: any
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  provider: ^6.0.5
  flutter_signin_button: ^2.0.0
  settings_ui: ^2.0.2
  carousel_slider: ^4.2.1
  modal_bottom_sheet: ^2.1.2

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon.png
