// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCedUwZjWznB0m81_nf9IY0CREOIQSNYIc',
    appId: '1:1018512304007:web:b3d446df1b1499f56b5522',
    messagingSenderId: '1018512304007',
    projectId: 'birthday-remainder-app',
    authDomain: 'birthday-remainder-app.firebaseapp.com',
    databaseURL: 'https://birthday-remainder-app.firebaseio.com',
    storageBucket: 'birthday-remainder-app.appspot.com',
    measurementId: 'G-TBPBYSD32G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCER1YAnYZxnaasCam2QEAQeApJos0L1G0',
    appId: '1:1018512304007:android:c5bcfb60f613e2a76b5522',
    messagingSenderId: '1018512304007',
    projectId: 'birthday-remainder-app',
    databaseURL: 'https://birthday-remainder-app.firebaseio.com',
    storageBucket: 'birthday-remainder-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeBgJIii0PJ6z0kaRHYKlxJ6Y2pBqq25Y',
    appId: '1:1018512304007:ios:a49fafd06ee38b9c6b5522',
    messagingSenderId: '1018512304007',
    projectId: 'birthday-remainder-app',
    databaseURL: 'https://birthday-remainder-app.firebaseio.com',
    storageBucket: 'birthday-remainder-app.appspot.com',
    androidClientId: '1018512304007-37g6mopnqacg7hsedrd7monil2rgjb6k.apps.googleusercontent.com',
    iosClientId: '1018512304007-60mk697phbofj0skvubs5banqdik6ph8.apps.googleusercontent.com',
    iosBundleId: 'net.tomascichero.birthdayremainder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeBgJIii0PJ6z0kaRHYKlxJ6Y2pBqq25Y',
    appId: '1:1018512304007:ios:a49fafd06ee38b9c6b5522',
    messagingSenderId: '1018512304007',
    projectId: 'birthday-remainder-app',
    databaseURL: 'https://birthday-remainder-app.firebaseio.com',
    storageBucket: 'birthday-remainder-app.appspot.com',
    androidClientId: '1018512304007-37g6mopnqacg7hsedrd7monil2rgjb6k.apps.googleusercontent.com',
    iosClientId: '1018512304007-60mk697phbofj0skvubs5banqdik6ph8.apps.googleusercontent.com',
    iosBundleId: 'net.tomascichero.birthdayremainder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEhq6sfilD8ln359byGMbrUy2R6pMRy2E',
    appId: '1:1018512304007:web:07c39be5187c82186b5522',
    messagingSenderId: '1018512304007',
    projectId: 'birthday-remainder-app',
    authDomain: 'birthday-remainder-app.firebaseapp.com',
    databaseURL: 'https://birthday-remainder-app.firebaseio.com',
    storageBucket: 'birthday-remainder-app.appspot.com',
    measurementId: 'G-RGVSGSXNRD',
  );
}
